name: Deploy to Remote Server

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Remote Server via SSH
        uses: appleboy/ssh-action@v0.1.10
        env:
          REPO: ${{ github.event.repository.name }}
          WS_PORT: 8080
        with:
          envs: REPO,WS_PORT
          host: ${{ vars.SSH_HOST }}
          port: ${{ vars.SSH_PORT }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            cd /home/github/$REPO
            forever stop $(forever list | grep "dist/server.js" | grep -v "STOPPED" | grep -oE '[0-9]+[ ]+[0-9]+' | grep -oEi ' [0-9]+' | grep -oE '[0-9]+')
            sudo kill -9 $(sudo netstat -peanut | grep ":8080 " | grep -oE '[0-9]+\/node$' | grep -oE '[0-9]+')
            git pull
            pnpm install
            pnpm build
            while [ $(sudo netstat -peanut | grep -c ":8080 ") -ne 0 ]; do echo "Waiting for port to free" && sleep 2; done;
            export WS_PORT=$WS_PORT && forever start -c 'sudo -E node' dist/server.js
